/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteProjectsRouteImport } from './routes/_site.projects'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin.admin.projects'
import { Route as AdminAdminPricelistsRouteImport } from './routes/_admin.admin.pricelists'
import { Route as AdminAdminAdminsRouteImport } from './routes/_admin.admin.admins'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPricelistsRoute = AdminAdminPricelistsRouteImport.update({
  id: '/pricelists',
  path: '/pricelists',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAdminsRoute = AdminAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/pricing': typeof SitePricingRoute
  '/projects': typeof SiteProjectsRoute
  '/admin/admins': typeof AdminAdminAdminsRoute
  '/admin/pricelists': typeof AdminAdminPricelistsRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/pricing': typeof SitePricingRoute
  '/projects': typeof SiteProjectsRoute
  '/admin/admins': typeof AdminAdminAdminsRoute
  '/admin/pricelists': typeof AdminAdminPricelistsRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/projects': typeof SiteProjectsRoute
  '/_site/': typeof SiteIndexRoute
  '/_admin/admin/admins': typeof AdminAdminAdminsRoute
  '/_admin/admin/pricelists': typeof AdminAdminPricelistsRoute
  '/_admin/admin/projects': typeof AdminAdminProjectsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/projects'
    | '/admin/admins'
    | '/admin/pricelists'
    | '/admin/projects'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/projects'
    | '/admin/admins'
    | '/admin/pricelists'
    | '/admin/projects'
    | '/admin'
  id:
    | '__root__'
    | '/_admin'
    | '/_site'
    | '/login'
    | '/_admin/admin'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/pricing'
    | '/_site/projects'
    | '/_site/'
    | '/_admin/admin/admins'
    | '/_admin/admin/pricelists'
    | '/_admin/admin/projects'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects': {
      id: '/_site/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pricelists': {
      id: '/_admin/admin/pricelists'
      path: '/pricelists'
      fullPath: '/admin/pricelists'
      preLoaderRoute: typeof AdminAdminPricelistsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/admins': {
      id: '/_admin/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminAdminsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAdminsRoute: typeof AdminAdminAdminsRoute
  AdminAdminPricelistsRoute: typeof AdminAdminPricelistsRoute
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAdminsRoute: AdminAdminAdminsRoute,
  AdminAdminPricelistsRoute: AdminAdminPricelistsRoute,
  AdminAdminProjectsRoute: AdminAdminProjectsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SitePricingRoute: SitePricingRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
